### ISSUE TITLE
Export Time tracked tasks to an accounting software or CSV

### ISSUE THREAD

**Issue by Carlos57000** [jakobsack/timetracker#2]
Hi, 

Is there currently a way to export the tasks tracked that appear on Nextcloud to external accounting softwares like Sage Bob or even Odoo?

If the answer is yes, is it a direct connection or an export in a format like CSV that has to be imported then?

**Comment by jakobsack** [comment]
Sorry, I guess you got the wrong repo. Were you looking for https://github.com/mtierltd/timetracker ?

**Comment by c33s** [comment]
the other repo is quite dead. having a export feature would really be awesome

**Comment by jakobsack** [comment]
This repo here is ***not*** related to the timetracker app from https://apps.nextcloud.com/apps/timetracker
I created it when I thought about creating a similar app, but did not get around to actually implement it.
Gonna delete this repo to stop the confusion.
