### ISSUE TITLE
Port records to other nextcloud 

### ISSUE THREAD

**Issue by yannick-reich** [jakobsack/timetracker#3]
Hi Jakob,

been using your app for a while now. Works great, thanks a lot!

I've now had to "resetup" my nextcloud and am wondering whether there is a way to get the records to the new instance. I have something like copying the right files from the old instance to the right places in the new instance in mind. Can you help me with that?

Best,
   Yannick

**Comment by jakobsack** [comment]
Sorry, I guess you got the wrong repo. Were you looking for https://github.com/mtierltd/timetracker ?
